"""
Tests for DeployX v0.1.5:
- Docker build PIP mirror support (PIP_INDEX_URL, PIP_EXTRA_INDEX_URL, PIP_TRUSTED_HOST)
- Docker Compose build args and unset mirror fallback
- Project-level mirror configuration in deployx.yml
- Environment override priority (env > config > default)
- URL credential redaction across logs, errors, and project info
- BuildKit rawjson event parsing and step tracking
- Current build step terminal visibility
- Stall warning context with current step and redacted index
- Deploy and update environment propagation
- DeployX-owned file regeneration and user-owned file overwrite protection
- CLI edit and generate commands
- Network precheck reachability
"""

import json
import base64
from pathlib import Path
from unittest.mock import MagicMock
import pytest
from rich.console import Console
from typer.testing import CliRunner

from deployx.cli import app
from deployx.core.command import run_command_streaming
from deployx.core.security import redact_sensitive_text, redact_url_credentials
from deployx.deployment.deploy import (
    check_package_index_reachability,
    resolve_build_environment,
    run_deployment,
)
from deployx.deployment.project import add_project, edit_project, load_project_config, show_project_info
from deployx.deployment.update import run_update
from deployx.detectors.base import DetectedInfrastructure, DetectionResult
from deployx.generators.django import (
    generate_compose_file,
    generate_django_dockerfile,
    is_deployx_generated_file,
)
from deployx.models import (
    BuildConfig,
    DeploymentConfig,
    DeploymentState,
    DockerConfig,
    FrameworkType,
    GitConfig,
    ProjectConfig,
    ProjectMeta,
    PythonBuildConfig,
)
from deployx.state import get_state_manager
from deployx.ui.progress import BuildKitParser, DeploymentProgressReporter


from deployx.config import paths, reload_paths


runner = CliRunner()


@pytest.fixture(autouse=True)
def isolated_deployx_env(tmp_path, monkeypatch, mocker):
    """Isolates DeployX directories into tmp_path for pristine tests."""
    root = tmp_path / "opt_deployx"
    etc = tmp_path / "etc_deployx"
    monkeypatch.setenv("DEPLOYX_ROOT", str(root))
    monkeypatch.setenv("DEPLOYX_CONFIG_DIR", str(etc))
    reload_paths()
    paths.ensure_all_dirs()

    mocker.patch(
        "deployx.deployment.project.verify_public_repository",
        return_value="f0222384a29ebcd90d80111bfbc7c1abf8da4e0f",
    )

    # Clean mirror env vars
    monkeypatch.delenv("PIP_INDEX_URL", raising=False)
    monkeypatch.delenv("PIP_EXTRA_INDEX_URL", raising=False)
    monkeypatch.delenv("PIP_TRUSTED_HOST", raising=False)


# ==============================================================================
# 1. Generated Dockerfile PIP_INDEX_URL Support & Deterministic Layer
# ==============================================================================
def test_generated_dockerfile_pip_support_and_deterministic_layer(tmp_path):
    config = ProjectConfig(
        project=ProjectMeta(name="myweb"),
        git=GitConfig(repository="https://github.com/myteam/myweb.git"),
    )
    # Case 1: Requirements without gunicorn declared
    detection = DetectionResult(
        framework=FrameworkType.DJANGO,
        confidence=1.0,
        matched_indicators=["requirements.txt"],
        infrastructure=DetectedInfrastructure(
            has_dockerfile=False,
            dependencies=["django", "psycopg2"],
            has_gunicorn=False,
        ),
    )
    df_path = tmp_path / "Dockerfile.deployx"
    generate_django_dockerfile(config, detection, df_path)

    content = df_path.read_text(encoding="utf-8")
    # Verify ARGs
    assert "ARG PIP_INDEX_URL" in content
    assert "ARG PIP_EXTRA_INDEX_URL" in content
    assert "ARG PIP_TRUSTED_HOST" in content
    assert "Auto-generated by DeployX for myweb" in content
    # Verify deterministic single layer with gunicorn appended
    assert "pip install --no-cache-dir -r requirements.txt;" in content
    assert "&& pip install --no-cache-dir gunicorn" in content

    # Case 2: Requirements with gunicorn already declared
    detection_with_gunicorn = DetectionResult(
        framework=FrameworkType.DJANGO,
        confidence=1.0,
        matched_indicators=["requirements.txt"],
        infrastructure=DetectedInfrastructure(
            has_dockerfile=False,
            dependencies=["django", "gunicorn"],
            has_gunicorn=True,
        ),
    )
    df_path2 = tmp_path / "Dockerfile_gunicorn.deployx"
    generate_django_dockerfile(config, detection_with_gunicorn, df_path2)
    content2 = df_path2.read_text(encoding="utf-8")
    assert "pip install --no-cache-dir -r requirements.txt;" in content2
    # Gunicorn should not be appended separately
    assert "&& pip install --no-cache-dir gunicorn" not in content2


# ==============================================================================
# 2. Generated Compose Build Args & Unset Behavior
# ==============================================================================
def test_generated_compose_build_args(tmp_path):
    config = ProjectConfig(
        project=ProjectMeta(name="composeapp"),
        git=GitConfig(repository="https://github.com/myteam/composeapp.git"),
    )
    detection = DetectionResult(
        framework=FrameworkType.DJANGO,
        confidence=1.0,
        matched_indicators=["manage.py"],
        infrastructure=DetectedInfrastructure(has_dockerfile=False),
    )
    compose_path = tmp_path / "docker-compose.deployx.yml"
    generate_compose_file(config, detection, "deployx_composeapp:abc1234", compose_path)

    content = compose_path.read_text(encoding="utf-8")
    assert "Auto-generated by DeployX for composeapp" in content
    assert "PIP_INDEX_URL: ${PIP_INDEX_URL:-}" in content
    assert "PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL:-}" in content
    assert "PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST:-}" in content


# ==============================================================================
# 3. Project Config Mirror Persistence & Environment Override Priority
# ==============================================================================
def test_project_mirror_config_and_env_override(monkeypatch):
    # Default behavior: unset
    cfg_default = ProjectConfig(
        project=ProjectMeta(name="testproj"),
        git=GitConfig(repository="https://github.com/company/myapp.git"),
    )
    assert resolve_build_environment(cfg_default) == {}

    # Config set: project level
    cfg_custom = ProjectConfig(
        project=ProjectMeta(name="testproj"),
        git=GitConfig(repository="https://github.com/company/myapp.git"),
        build=BuildConfig(
            python=PythonBuildConfig(
                index_url="https://mirrors.aliyun.com/pypi/simple/",
                extra_index_url="https://extra.mirror.com/simple/",
                trusted_host="mirrors.aliyun.com",
            )
        ),
    )
    env_resolved = resolve_build_environment(cfg_custom)
    assert env_resolved["PIP_INDEX_URL"] == "https://mirrors.aliyun.com/pypi/simple/"
    assert env_resolved["PIP_EXTRA_INDEX_URL"] == "https://extra.mirror.com/simple/"
    assert env_resolved["PIP_TRUSTED_HOST"] == "mirrors.aliyun.com"

    # Environment override priority: os.environ > config
    monkeypatch.setenv("PIP_INDEX_URL", "https://override.mirror.com/simple/")
    env_overridden = resolve_build_environment(cfg_custom)
    assert env_overridden["PIP_INDEX_URL"] == "https://override.mirror.com/simple/"
    # Unoverridden extra still comes from config
    assert env_overridden["PIP_EXTRA_INDEX_URL"] == "https://extra.mirror.com/simple/"


# ==============================================================================
# 4. Credential Redaction in URLs and Logs
# ==============================================================================
def test_credential_redaction_urls_and_text():
    url_with_creds = "https://myuser:secretpass123@mirror.example.com/pypi/simple/"
    redacted = redact_url_credentials(url_with_creds)
    assert redacted == "https://myuser:***@mirror.example.com/pypi/simple/"
    assert "secretpass123" not in redacted

    token_url = "http://my_auth_token@internal.mirror.local/simple"
    redacted_token = redact_url_credentials(token_url)
    assert redacted_token == "http://***@internal.mirror.local/simple"
    assert "my_auth_token" not in redacted_token

    log_entry = (
        "Running: pip install --index-url https://admin:super_secret@pypi.company.com/simple/ requests\n"
        "DATABASE_PASSWORD=production_secret_pw\n"
    )
    redacted_log = redact_sensitive_text(log_entry)
    assert "super_secret" not in redacted_log
    assert "production_secret_pw" not in redacted_log
    assert "https://admin:***@pypi.company.com/simple/" in redacted_log


# ==============================================================================
# 5. DeployX-Owned File Regeneration vs User-Owned Protection
# ==============================================================================
def test_deployx_file_regeneration_and_user_protection(tmp_path):
    generated_file = tmp_path / "Dockerfile.deployx"
    generated_file.write_text(
        "# ==============================================================================\n"
        "# Auto-generated by DeployX for testproj\n"
        "# ==============================================================================\n"
        "FROM python:3.12-slim\n",
        encoding="utf-8",
    )
    assert is_deployx_generated_file(generated_file) is True

    user_file = tmp_path / "Dockerfile"
    user_file.write_text("FROM python:3.11-alpine\n# Handcrafted by developer\n", encoding="utf-8")
    assert is_deployx_generated_file(user_file) is False

    modified_file = tmp_path / "custom_dockerfile.deployx"
    modified_file.write_text("FROM ubuntu:24.04\nRUN apt update\n", encoding="utf-8")
    assert is_deployx_generated_file(modified_file) is False


def test_deploy_protects_user_owned_files(mocker, tmp_path):
    console = Console(record=True)
    add_project(
        name="userprot",
        git="https://github.com/myorg/myapp.git",
        branch="main",
        console=console,
    )
    from deployx.config import paths
    pdir = paths.get_project_dir("userprot")
    pdir.mkdir(parents=True, exist_ok=True)

    # Place a user-owned Dockerfile without marker
    user_df = pdir / "Dockerfile.deployx"
    user_df.write_text("# Custom developer file without marker\nFROM python:3.10\n", encoding="utf-8")

    mocker.patch("deployx.deployment.deploy.GitRepositoryManager.sync_repository", return_value="f0222384a29ebcd90d80111bfbc7c1abf8da4e0f")
    mocker.patch("deployx.deployment.deploy.detect_repository", return_value=DetectionResult(
        framework=FrameworkType.DJANGO,
        confidence=1.0,
        matched_indicators=["requirements.txt"],
        infrastructure=DetectedInfrastructure(has_dockerfile=False),
    ))
    mock_cmd = MagicMock(success=True, returncode=0, stdout="", stderr="")
    mocker.patch("deployx.docker.compose.DockerComposeManager.build", return_value=mock_cmd)
    mocker.patch("deployx.docker.compose.DockerComposeManager.up", return_value=mock_cmd)
    mocker.patch("deployx.docker.compose.DockerComposeManager.run_transient", return_value=mock_cmd)
    mocker.patch("deployx.deployment.deploy.perform_http_healthcheck", return_value=True)

    # Run deployment without --regenerate
    res = run_deployment("userprot", console=console)
    assert res is True
    # Verify user-owned content was NOT overwritten
    assert "Custom developer file without marker" in user_df.read_text(encoding="utf-8")


# ==============================================================================
# 6. BuildKit rawjson Parsing
# ==============================================================================
def test_buildkit_rawjson_parsing():
    parser = BuildKitParser()

    # Rawjson event with vertex name
    json_event1 = json.dumps({
        "vertex": {
            "name": "[5/8] RUN pip install --no-cache-dir -r requirements.txt",
            "digest": "sha256:12345",
        }
    })
    parser.parse_line(json_event1)
    assert parser.step_current == 5
    assert parser.step_total == 8
    assert parser.approx_percent == 62
    assert "pip install" in parser.current_operation
    assert parser.is_network_operation() is True

    # Rawjson with statuses
    json_event2 = json.dumps({
        "statuses": [
            {
                "id": "step-6",
                "name": "[6/8] COPY . /app/",
                "current": 6,
                "total": 8,
            }
        ]
    })
    parser.parse_line(json_event2)
    assert parser.step_current == 6
    assert parser.step_total == 8
    assert "COPY" in parser.current_operation

    # Rawjson with base64 encoded log data
    encoded_log = base64.b64encode(b"Collecting requests==2.31.0\nDownloading requests.whl").decode("utf-8")
    json_event3 = json.dumps({
        "logs": [
            {"vertex": "sha256:123", "data": encoded_log}
        ]
    })
    parser.parse_line(json_event3)
    assert any("Collecting requests" in l for l in parser.last_relevant_lines)


# ==============================================================================
# 7. Current Build Step Display & Stall Warning Context
# ==============================================================================
def test_build_step_visibility_and_stall_context():
    console = Console(record=True)
    reporter = DeploymentProgressReporter(
        "herbal_web",
        console=console,
        python_index="https://user:mypassword@mirrors.aliyun.com/pypi/simple/",
    )

    # Stream a rawjson line
    raw_step = json.dumps({"vertex": {"name": "[5/8] RUN pip install --no-cache-dir -r requirements.txt"}})
    reporter.on_build_output(raw_step)

    output = console.export_text()
    assert "Build step 5/8" in output or "Step 5/8" in output
    assert "RUN pip install" in output

    # Trigger stall warning
    reporter.on_stall(elapsed=125.0, idle=120.0)
    stall_output = console.export_text()

    assert "WARNING:" in stall_output
    assert "120 seconds" in stall_output
    assert "Current build step:" in stall_output
    assert "RUN pip install --no-cache-dir -r requirements.txt" in stall_output
    assert "Possible network/package index issue." in stall_output
    assert "Configured Python index:" in stall_output
    assert "Custom (https://user:***@mirrors.aliyun.com/pypi/simple/)" in stall_output
    assert "mypassword" not in stall_output


# ==============================================================================
# 8. Environment Propagation in Deploy and Update
# ==============================================================================
def test_deploy_environment_propagation(mocker, monkeypatch):
    console = Console(record=True)
    add_project(
        name="envprop",
        git="https://github.com/myorg/myapp.git",
        branch="main",
        console=console,
    )
    monkeypatch.setenv("PIP_INDEX_URL", "https://mirrors.aliyun.com/pypi/simple/")

    mocker.patch("deployx.deployment.deploy.GitRepositoryManager.sync_repository", return_value="f0222384a29ebcd90d80111bfbc7c1abf8da4e0f")
    mocker.patch("deployx.deployment.deploy.detect_repository", return_value=DetectionResult(
        framework=FrameworkType.DJANGO,
        confidence=1.0,
        matched_indicators=["requirements.txt"],
        infrastructure=DetectedInfrastructure(has_dockerfile=False),
    ))
    mock_cmd = MagicMock(success=True, returncode=0, stdout="", stderr="")
    mock_build = mocker.patch("deployx.docker.compose.DockerComposeManager.build", return_value=mock_cmd)
    mocker.patch("deployx.docker.compose.DockerComposeManager.up", return_value=mock_cmd)
    mocker.patch("deployx.docker.compose.DockerComposeManager.run_transient", return_value=mock_cmd)
    mocker.patch("deployx.deployment.deploy.perform_http_healthcheck", return_value=True)

    res = run_deployment("envprop", console=console)
    assert res is True
    # Verify build was called with env containing PIP_INDEX_URL
    mock_build.assert_called_once()
    _, kwargs = mock_build.call_args
    passed_env = kwargs.get("env", {})
    assert passed_env.get("PIP_INDEX_URL") == "https://mirrors.aliyun.com/pypi/simple/"


# ==============================================================================
# 9. CLI Project Edit and Info with Pip Mirror & Redaction
# ==============================================================================
def test_cli_project_edit_pip_mirror_and_info():
    console = Console(record=True)
    add_project(
        name="editapp",
        git="https://github.com/myorg/myapp.git",
        branch="main",
        console=console,
    )

    # Edit via function
    edit_project(
        project_name="editapp",
        pip_index_url="https://secuser:secpass@mirror.example.com/pypi/simple/",
        pip_extra_index_url="https://extra.example.com/simple/",
        pip_trusted_host="mirror.example.com",
        yes=True,
        console=console,
    )

    cfg = load_project_config("editapp")
    assert cfg.build.python.index_url == "https://secuser:secpass@mirror.example.com/pypi/simple/"
    assert cfg.build.python.extra_index_url == "https://extra.example.com/simple/"
    assert cfg.build.python.trusted_host == "mirror.example.com"

    # Info display
    info_console = Console(record=True)
    show_project_info("editapp", console=info_console)
    info_text = info_console.export_text()
    assert "Python Package Index: Custom" in info_text
    assert "https://secuser:***@mirror.example.com/pypi/simple/" in info_text
    assert "secpass" not in info_text


# ==============================================================================
# 10. CLI Generate Command
# ==============================================================================
def test_cli_generate_command(mocker):
    console = Console(record=True)
    add_project(
        name="genapp",
        git="https://github.com/myorg/myapp.git",
        branch="main",
        console=console,
    )
    from deployx.config import paths
    pdir = paths.get_project_dir("genapp")
    pdir.mkdir(parents=True, exist_ok=True)

    res = runner.invoke(app, ["generate", "genapp"])
    assert res.exit_code == 0
    assert (pdir / "Dockerfile.deployx").is_file()
    assert (pdir / "docker-compose.deployx.yml").is_file()
    assert is_deployx_generated_file(pdir / "Dockerfile.deployx") is True
    assert is_deployx_generated_file(pdir / "docker-compose.deployx.yml") is True


# ==============================================================================
# 11. Network Precheck Function
# ==============================================================================
def test_package_index_precheck_handling(mocker):
    # Success case
    mocker.patch("urllib.request.urlopen", return_value=MagicMock(__enter__=MagicMock(return_value=MagicMock(status=200))))
    ok, msg = check_package_index_reachability("https://mirrors.aliyun.com/pypi/simple/")
    assert ok is True
    assert "Reachable" in msg

    # Failure case: does not crash
    mocker.patch("urllib.request.urlopen", side_effect=Exception("Connection timed out"))
    ok_fail, msg_fail = check_package_index_reachability("https://unreachable.mirror.xyz/")
    assert ok_fail is False
    assert "Connection timed out" in msg_fail
