"""
DeployX Django Docker & Compose Generator
Generates Dockerfile.deployx (if missing in repo) and docker-compose.deployx.yml.
Strictly protects existing repository configuration files.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional
import yaml

from deployx.config import paths
from deployx.core.filesystem import atomic_write_file
from deployx.core.security import validate_project_name
from deployx.detectors.base import DetectionResult
from deployx.models import DatabasePreference, ProjectConfig


def generate_django_dockerfile(
    project_config: ProjectConfig,
    detection: DetectionResult,
    target_path: Path,
) -> Path:
    """
    Generates a production Dockerfile for Django:
    - Multi-stage or optimized single-stage Debian slim image.
    - System dependencies (libpq-dev for PostgreSQL, curl for healthchecks).
    - In-container dependencies installation.
    - Non-root user for security.
    """
    wsgi_cmd = detection.infrastructure.wsgi_module or "core.wsgi:application"

    content = f"""# ==============================================================================
# Auto-generated by DeployX for {project_config.project.name}
# ==============================================================================
FROM python:3.12-slim-bookworm

ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    PORT=8000

WORKDIR /app

# Install minimal OS dependencies for PostgreSQL and healthchecks
RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    libpq-dev \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install
COPY requirements*.txt /app/
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
RUN pip install --no-cache-dir gunicorn

# Copy full application codebase
COPY . /app/

# Create non-root user
RUN addgroup --system deployx && adduser --system --group deployx \\
    && mkdir -p /app/staticfiles /app/media \\
    && chown -R deployx:deployx /app

USER deployx

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "--timeout", "60", "{wsgi_cmd}"]
"""
    atomic_write_file(target_path, content, mode=0o644)
    return target_path


def generate_compose_file(
    project_config: ProjectConfig,
    detection: DetectionResult,
    docker_image_tag: str,
    target_path: Path,
) -> Path:
    """
    Generates /opt/deployx/projects/<project>/docker-compose.deployx.yml.
    Preserves repo isolation using project-specific networks and named volumes.
    """
    pname = validate_project_name(project_config.project.name)
    infra = detection.infrastructure

    # Check if project has an existing Dockerfile in repo
    if infra.has_dockerfile and infra.dockerfile_path:
        dockerfile_rel = infra.dockerfile_path.name
    else:
        # Reference generated Dockerfile
        dockerfile_rel = "../Dockerfile.deployx"

    health_path = project_config.deployment.healthcheck.path or "/"
    web_port = project_config.deployment.docker.port

    services: Dict[str, Any] = {}
    volumes: Dict[str, Any] = {
        "static_volume": {"name": f"deployx_{pname}_static"},
        "media_volume": {"name": f"deployx_{pname}_media"},
    }

    # 1. Web application service
    services["web"] = {
        "image": docker_image_tag,
        "build": {
            "context": "./repo",
            "dockerfile": dockerfile_rel,
        },
        "container_name": f"deployx_{pname}_web",
        "restart": "unless-stopped",
        "env_file": [".env.production"],
        "ports": [f"127.0.0.1:{web_port}:8000"],
        "volumes": [
            "static_volume:/app/staticfiles",
            "media_volume:/app/media",
        ],
        "networks": ["deployx_network"],
        "healthcheck": {
            "test": [
                "CMD-SHELL",
                f"curl -f http://localhost:8000{health_path} || exit 1",
            ],
            "interval": f"{project_config.deployment.healthcheck.interval}s",
            "timeout": f"{project_config.deployment.healthcheck.timeout}s",
            "retries": project_config.deployment.healthcheck.retries,
            "start_period": "10s",
        },
    }

    depends_on: Dict[str, Any] = {}

    # 2. Database service (PostgreSQL)
    if project_config.deployment.database == DatabasePreference.POSTGRES or infra.has_postgres:
        services["db"] = {
            "image": "postgres:16-alpine",
            "container_name": f"deployx_{pname}_db",
            "restart": "unless-stopped",
            "env_file": [".env.production"],
            "volumes": ["postgres_data:/var/lib/postgresql/data"],
            "networks": ["deployx_network"],
            "healthcheck": {
                "test": ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"],
                "interval": "5s",
                "timeout": "5s",
                "retries": 5,
            },
        }
        volumes["postgres_data"] = {"name": f"deployx_{pname}_pgdata"}
        depends_on["db"] = {"condition": "service_healthy"}

    # 3. Redis service
    if project_config.deployment.redis or infra.has_redis:
        services["redis"] = {
            "image": "redis:7-alpine",
            "container_name": f"deployx_{pname}_redis",
            "restart": "unless-stopped",
            "volumes": ["redis_data:/data"],
            "networks": ["deployx_network"],
            "healthcheck": {
                "test": ["CMD", "redis-cli", "ping"],
                "interval": "5s",
                "timeout": "3s",
                "retries": 3,
            },
        }
        volumes["redis_data"] = {"name": f"deployx_{pname}_redisdata"}
        depends_on["redis"] = {"condition": "service_healthy"}

    if depends_on:
        services["web"]["depends_on"] = depends_on

    compose_dict = {
        "name": f"deployx_{pname}",
        "services": services,
        "volumes": volumes,
        "networks": {
            "deployx_network": {
                "name": f"deployx_{pname}_net",
                "driver": "bridge",
            }
        },
    }

    content = yaml.dump(compose_dict, sort_keys=False, default_flow_style=False)
    atomic_write_file(target_path, content, mode=0o644)
    return target_path
