"""
DeployX FastAPI Docker & Compose Generator
Generates Dockerfile.deployx and docker-compose.deployx.yml for FastAPI applications.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict
import yaml

from deployx.config import paths
from deployx.core.filesystem import atomic_write_file
from deployx.core.security import validate_project_name
from deployx.detectors.base import DetectionResult
from deployx.models import DatabasePreference, ProjectConfig


def generate_fastapi_dockerfile(
    project_config: ProjectConfig,
    detection: DetectionResult,
    target_path: Path,
) -> Path:
    infra = detection.infrastructure
    asgi_cmd = infra.asgi_module or "main:app"
    py_version = infra.selected_python_version or "3.12"
    pkg_mgr = infra.package_manager or "pip"

    deps = [d.lower() for d in getattr(infra, "dependencies", [])]
    has_uvicorn = "uvicorn" in deps or "granian" in deps

    if pkg_mgr == "poetry":
        copy_step = "COPY pyproject.toml poetry.lock* /app/"
        install_cmd = (
            "RUN pip install --no-cache-dir poetry \\\n"
            "    && poetry config virtualenvs.create false \\\n"
            "    && poetry install --no-root --no-interaction"
        )
    elif pkg_mgr == "uv":
        copy_step = "COPY pyproject.toml uv.lock* requirements*.txt* /app/"
        install_cmd = (
            "RUN pip install --no-cache-dir uv \\\n"
            "    && if [ -f uv.lock ]; then uv pip install --system -r pyproject.toml; \\\n"
            "       elif [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi"
        )
    else:
        copy_step = "COPY requirements*.txt /app/"
        if has_uvicorn:
            install_cmd = (
                "RUN if [ -f requirements.txt ]; then \\\n"
                "      pip install --no-cache-dir -r requirements.txt; \\\n"
                "    fi"
            )
        else:
            install_cmd = (
                "RUN if [ -f requirements.txt ]; then \\\n"
                "      pip install --no-cache-dir -r requirements.txt; \\\n"
                "    fi \\\n"
                "    && pip install --no-cache-dir uvicorn[standard]"
            )

    content = f"""# ==============================================================================
# Auto-generated by DeployX for {project_config.project.name}
# ==============================================================================
FROM python:{py_version}-slim-bookworm

ARG PIP_INDEX_URL
ARG PIP_EXTRA_INDEX_URL
ARG PIP_TRUSTED_HOST

ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PORT=8000

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

{copy_step}
{install_cmd}

COPY . /app/

RUN addgroup --system deployx && adduser --system --group deployx \\
    && chown -R deployx:deployx /app

USER deployx

EXPOSE 8000

CMD ["uvicorn", "{asgi_cmd}", "--host", "0.0.0.0", "--port", "8000"]
"""
    atomic_write_file(target_path, content, mode=0o644)
    return target_path


def generate_fastapi_compose_file(
    project_config: ProjectConfig,
    detection: DetectionResult,
    docker_image_tag: str,
    target_path: Path,
) -> Path:
    pname = validate_project_name(project_config.project.name)
    infra = detection.infrastructure
    from deployx import __version__

    health_path = infra.health_endpoint or project_config.deployment.healthcheck.path or "/"
    web_port = project_config.deployment.docker.port
    deployx_labels = {
        "com.deployx.managed": "true",
        "com.deployx.project": pname,
        "com.deployx.version": __version__,
    }

    dockerfile_rel = infra.dockerfile_path.name if (infra.has_dockerfile and infra.dockerfile_path) else "../Dockerfile.deployx"

    services: Dict[str, Any] = {
        "web": {
            "image": docker_image_tag,
            "build": {
                "context": "./repo",
                "dockerfile": dockerfile_rel,
                "args": {
                    "PIP_INDEX_URL": "${PIP_INDEX_URL:-}",
                    "PIP_EXTRA_INDEX_URL": "${PIP_EXTRA_INDEX_URL:-}",
                    "PIP_TRUSTED_HOST": "${PIP_TRUSTED_HOST:-}",
                },
            },
            "container_name": f"deployx_{pname}_web",
            "restart": "unless-stopped",
            "labels": deployx_labels.copy(),
            "env_file": [".env.production"],
            "ports": [f"127.0.0.1:{web_port}:8000"],
            "networks": ["deployx_network"],
            "healthcheck": {
                "test": ["CMD-SHELL", f"curl -f http://localhost:8000{health_path} || exit 1"],
                "interval": "5s",
                "timeout": "5s",
                "retries": 5,
                "start_period": "5s",
            },
        }
    }

    volumes: Dict[str, Any] = {}
    depends_on: Dict[str, Any] = {}

    if project_config.deployment.database == DatabasePreference.POSTGRES or infra.has_postgres:
        services["db"] = {
            "image": "postgres:16-alpine",
            "container_name": f"deployx_{pname}_db",
            "restart": "unless-stopped",
            "labels": deployx_labels.copy(),
            "env_file": [".env.production"],
            "volumes": ["postgres_data:/var/lib/postgresql/data"],
            "networks": ["deployx_network"],
            "healthcheck": {
                "test": ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"],
                "interval": "5s",
                "timeout": "5s",
                "retries": 5,
            },
        }
        volumes["postgres_data"] = {
            "name": f"deployx_{pname}_pgdata",
            "labels": deployx_labels.copy(),
        }
        depends_on["db"] = {"condition": "service_healthy"}

    if project_config.deployment.redis or infra.has_redis:
        services["redis"] = {
            "image": "redis:7-alpine",
            "container_name": f"deployx_{pname}_redis",
            "restart": "unless-stopped",
            "labels": deployx_labels.copy(),
            "volumes": ["redis_data:/data"],
            "networks": ["deployx_network"],
        }
        volumes["redis_data"] = {
            "name": f"deployx_{pname}_redisdata",
            "labels": deployx_labels.copy(),
        }
        depends_on["redis"] = {"condition": "service_started"}

    if depends_on:
        services["web"]["depends_on"] = depends_on

    compose_dict = {
        "name": f"deployx_{pname}",
        "services": services,
        "volumes": volumes,
        "networks": {
            "deployx_network": {
                "name": f"deployx_{pname}_net",
                "driver": "bridge",
                "labels": deployx_labels.copy(),
            }
        },
    }

    header = (
        f"# ==============================================================================\n"
        f"# Auto-generated by DeployX for {project_config.project.name}\n"
        f"# ==============================================================================\n"
    )
    content = header + yaml.dump(compose_dict, sort_keys=False, default_flow_style=False)
    atomic_write_file(target_path, content, mode=0o644)
    return target_path
