"""
DeployX Generic Python Docker & Compose Generator
Generates Dockerfile.deployx and docker-compose.deployx.yml for Generic Python applications.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict
import yaml

from deployx.config import paths
from deployx.core.filesystem import atomic_write_file
from deployx.core.security import validate_project_name
from deployx.detectors.base import DetectionResult
from deployx.models import DatabasePreference, ProjectConfig


def generate_generic_dockerfile(
    project_config: ProjectConfig,
    detection: DetectionResult,
    target_path: Path,
) -> Path:
    infra = detection.infrastructure
    py_version = infra.selected_python_version or "3.12"
    pkg_mgr = infra.package_manager or "pip"
    deps = [d.lower() for d in getattr(infra, "dependencies", [])]

    if infra.asgi_module:
        cmd_str = f'CMD ["uvicorn", "{infra.asgi_module}", "--host", "0.0.0.0", "--port", "8000"]'
    elif infra.wsgi_module:
        cmd_str = f'CMD ["gunicorn", "{infra.wsgi_module}", "--bind", "0.0.0.0:8000", "--workers", "3"]'
    elif (target_path.parent / "main.py").is_file():
        cmd_str = 'CMD ["python", "main.py"]'
    elif (target_path.parent / "app.py").is_file():
        cmd_str = 'CMD ["python", "app.py"]'
    else:
        cmd_str = 'CMD ["python", "main.py"]'

    if pkg_mgr == "poetry":
        copy_step = "COPY pyproject.toml poetry.lock* /app/"
        install_cmd = (
            "RUN pip install --no-cache-dir poetry \\\n"
            "    && poetry config virtualenvs.create false \\\n"
            "    && poetry install --no-root --no-interaction"
        )
    elif pkg_mgr == "uv":
        copy_step = "COPY pyproject.toml uv.lock* requirements*.txt* /app/"
        install_cmd = (
            "RUN pip install --no-cache-dir uv \\\n"
            "    && if [ -f uv.lock ]; then uv pip install --system -r pyproject.toml; \\\n"
            "       elif [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi"
        )
    else:
        copy_step = "COPY requirements*.txt /app/"
        install_cmd = (
            "RUN if [ -f requirements.txt ]; then \\\n"
            "      pip install --no-cache-dir -r requirements.txt; \\\n"
            "    fi"
        )

    content = f"""# ==============================================================================
# Auto-generated by DeployX for {project_config.project.name}
# ==============================================================================
FROM python:{py_version}-slim-bookworm

ARG PIP_INDEX_URL
ARG PIP_EXTRA_INDEX_URL
ARG PIP_TRUSTED_HOST

ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PORT=8000

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

{copy_step}
{install_cmd}

COPY . /app/

RUN addgroup --system deployx && adduser --system --group deployx \\
    && chown -R deployx:deployx /app

USER deployx

EXPOSE 8000

{cmd_str}
"""
    atomic_write_file(target_path, content, mode=0o644)
    return target_path


def generate_generic_compose_file(
    project_config: ProjectConfig,
    detection: DetectionResult,
    image_tag: str,
    target_path: Path,
) -> Path:
    project_name = validate_project_name(project_config.project.name)
    host_port = project_config.deployment.docker.port
    network_name = f"deployx_{project_name}_network"

    has_db = (
        project_config.deployment.database == DatabasePreference.POSTGRES
        or detection.infrastructure.has_postgres
    )
    has_redis = (
        project_config.deployment.redis
        or detection.infrastructure.has_redis
    )

    services: Dict[str, Any] = {}
    volumes: Dict[str, Any] = {}

    web_env = {
        "ENV_FILE": ".env.production",
        "PORT": "8000",
    }
    web_depends_on = []

    if has_db:
        db_service_name = "db"
        web_depends_on.append(db_service_name)
        db_vol = f"deployx_{project_name}_pgdata"
        volumes[db_vol] = {"name": db_vol}
        services[db_service_name] = {
            "image": "postgres:16-alpine",
            "restart": "unless-stopped",
            "environment": {
                "POSTGRES_DB": f"{project_name}_db",
                "POSTGRES_USER": f"{project_name}_user",
                "POSTGRES_PASSWORD_FILE": "/run/secrets/db_password",
            },
            "volumes": [
                f"{db_vol}:/var/lib/postgresql/data",
            ],
            "networks": [network_name],
            "healthcheck": {
                "test": ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"],
                "interval": "5s",
                "timeout": "5s",
                "retries": 5,
            },
        }

    if has_redis:
        redis_service_name = "redis"
        web_depends_on.append(redis_service_name)
        services[redis_service_name] = {
            "image": "redis:7-alpine",
            "restart": "unless-stopped",
            "networks": [network_name],
            "healthcheck": {
                "test": ["CMD", "redis-cli", "ping"],
                "interval": "5s",
                "timeout": "3s",
                "retries": 5,
            },
        }

    web_service: Dict[str, Any] = {
        "image": image_tag,
        "restart": "unless-stopped",
        "ports": [f"{host_port}:8000"],
        "env_file": [".env.production"],
        "networks": [network_name],
        "healthcheck": {
            "test": [
                "CMD",
                "curl",
                "-f",
                f"http://localhost:8000{project_config.deployment.healthcheck.path}",
            ],
            "interval": f"{project_config.deployment.healthcheck.interval}s",
            "timeout": f"{project_config.deployment.healthcheck.timeout}s",
            "retries": project_config.deployment.healthcheck.retries,
            "start_period": "10s",
        },
    }

    if web_depends_on:
        web_service["depends_on"] = {
            dep: {"condition": "service_healthy"} for dep in web_depends_on
        }

    services["web"] = web_service

    compose_data: Dict[str, Any] = {
        "name": f"deployx_{project_name}",
        "services": services,
        "networks": {
            network_name: {
                "name": network_name,
                "driver": "bridge",
            }
        },
    }

    if volumes:
        compose_data["volumes"] = volumes

    content = (
        f"# ==============================================================================\n"
        f"# Auto-generated by DeployX for {project_name}\n"
        f"# DO NOT EDIT DIRECTLY UNLESS DETACHING FROM DEPLOYX MANAGEMENT\n"
        f"# ==============================================================================\n\n"
        + yaml.dump(compose_data, sort_keys=False, default_flow_style=False)
    )

    atomic_write_file(target_path, content, mode=0o644)
    return target_path
